<?php

const PREFIXO_FONTE = "[LICITANET] - ";

const CONFIG_INSTRUMENTO_EDITAL = 1;
const CONFIG_INSTRUMENTO_AVISO  = 2;
const CONFIG_INSTRUMENTO_ATO = 3;

/** Instruments */
const CONFIG_TIPO_PROCESSO_PREGAO = 1;
const CONFIG_TIPO_PROCESSO_CONCORRENCIA = 3;
const CONFIG_TIPO_PROCESSO_DISPENSA = 2;
const CONFIG_TIPO_INEXIGIBILIDADE = 4;
const CONFIG_TIPO_COMPRA_DIRETA = 5;
const CONFIG_TIPO_LEILAO_ELETRONICO = 6;
const CONFIG_TIPO_PREGAO_PRESENCIAL = 7;
